on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwregistry.azurecr.io
        username: ${{secrets.acr_diaggarwregistry_username}}
        password: ${{secrets.acr_diaggarwregistry_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t diaggarwregistry.azurecr.io/aaaaatiwarishubaks2830:${{github.sha}}
        docker push diaggarwregistry.azurecr.io/aaaaatiwarishubaks2830:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_aaaaatiwarishubaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aaaaatiwarishubaks0cc5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aaaaatiwarishubaks0cc5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aaaaatiwarishubaks0cc5
        container-registry-url: diaggarwregistry.azurecr.io
        container-registry-username: ${{secrets.acr_diaggarwregistry_username}}
        container-registry-password: ${{secrets.acr_diaggarwregistry_password}}
        secret-name: aaaaatiwarisdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aaaaatiwarishubaks0cc5
        manifests: |
          manifests/deployment-94f8.yml
          manifests/service-94f8.yml
        images: |
          diaggarwregistry.azurecr.io/aaaaatiwarishubaks2830:${{github.sha}}
        imagepullsecrets: |
          aaaaatiwarisdockerauth